package siivous;
// Generated by ComTest BEGIN
import fi.jyu.mit.ohj2.Suuntaaja;
import static org.junit.Assert.*;
import org.junit.*;
import siivous.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.04.01 20:31:00 // Generated by ComTest
 *
 */
public class TyokohdeTest {



  // Generated by ComTest BEGIN
  /** 
   * testRekisteroi91 
   * @throws SailoException when error
   */
  @Test
  public void testRekisteroi91() throws SailoException {    // Tyokohde: 91
    Tyokohde t = new Tyokohde(), t2 = new Tyokohde(); 
    Tyokohde kohdedatasta = new Tyokohde(" 1 |Kauppa Kallis|Sepänkatu 2 |40100|Jyväskylä      |0022020 |Kauppias Mika|12-31313 |123-3210|0123   |2          |2|roskikset kerran viikossa|"); 
    t.rekisteroi(); 
    t2.rekisteroi(); 
    assertEquals("From: Tyokohde line: 97", 2, kohdedatasta.getTyontekijaNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTulosta120 
   * @throws SailoException when error
   */
  @Test
  public void testTulosta120() throws SailoException {    // Tyokohde: 120
    Tyokohde kohdedatasta = new Tyokohde(" 1 |Kauppa Kallis|Sepänkatu 2 |40100|Jyväskylä      |0022020 |Kauppias Mika|12-31313 |123-3210|0123   |2          |2|roskikset kerran viikossa|"); 
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    kohdedatasta.tulosta(System.out); 
    String tulos = "Työkohde\nKauppa Kallis\nOsoite: Sepänkatu 2, 40100 Jyväskylä\nKohteen numero:0022020\nYhteyshenkilö:Kauppias Mika puh: 12-31313\nAvaimen nro: 123-3210 hälytyskoodi: 0123\nTavoiteaika: 2.0\nLisätietoja: roskikset kerran viikossa\nTyöntekijän numero: 2\n\n"; 
    assertEquals("From: Tyokohde line: 126", null, so.ero(tulos)); 
    so.palauta(); 
  } // Generated by ComTest END
}